config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'
  resources :comments, only: [:create, :destroy]

  resources :blogs do
    member do
      put 'like', to: 'blogs#upvote'
      put 'dislike', to: 'blogs#downvote'
    end
  end

  resources :notices do
    member do
      put 'like', to: 'notices#upvote'
      put 'dislike', to: 'notices#downvote'
    end
  end

  resources :talks do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
  end

  resources :questions do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
    resources :answers
  end

  resources :galleries
  resources :markets
  resources :jobs
  resources :user_point_logs

  #intro
  get 'intro', :to=>'intro#index', as: 'intro'
  get 'privacy', :to=>'intro#privacy', as: 'privacy'
  get 'agreement', :to=>'intro#agreement', as: 'agreement'
  get 'mypage',:to=>'users#index', as: 'mypage'
  get 'tags/:tag', to: 'tags#index', as: :tag

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리사용자
  devise_for :admins, :controllers => {  :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'complete',:sign_in => 'login', :sign_out => 'logout'}

  # 관리자
  scope 'admin', module: 'admin', as: 'admin' do
    root to: 'home#index'

    resources :admins
    resources :users
    resources :galleries
    resources :markets
    resources :jobs
    resources :talks
    resources :galleries
    resources :blogs
    resources :comments
    resources :notices
    resources :questions
    resources :answers
    resources :blogs
    resources :blog_categories
  end
end

app/views/layouts/admin/_aside.html.erb
<aside id="main-menu" class="col-12 col-md-3 col-lg-2 col-xl-1">
  <h1 class="col-12"><%= link_to t(:service_name), admin_root_path %></h1>
  <nav>
    <ul class="nav">
      <li class="nav-item
            <% if ['admin/users'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_users_path, :class => "nav-link" do %>
          <i class="material-icons">payment</i><span><%= t(:user,scope:[:activerecord,:models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/blogs','admin/blog_categories'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_blogs_path, :class => "nav-link" do %>
          <i class="material-icons">settings</i><span><%= t(:blog,scope:[:activerecord,:models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/questions'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_questions_path, :class => "nav-link" do %>
          <i class="material-icons">settings</i><span><%= t(:question,scope:[:activerecord,:models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/jobs','admin/markets'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_jobs_path, :class => "nav-link" do %>
          <i class="material-icons">settings</i><span><%= t(:job,scope:[:activerecord,:models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/talks','admin/notices'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_talks_path, :class => "nav-link" do %>
          <i class="material-icons">settings</i><span><%= t(:talk,scope:[:activerecord,:models]) %></span>
        <% end %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <address class="col-12 col-lg-9">
        <a href="https://www.jedaeroweb.co.kr" target="_blank"><%=t(:jedearoweb) %></a>
        &nbsp;&nbsp; CopyLeft. 2020, jedaeroweb. All wrongs reserved.</address>
      <div class="col-12 col-lg-3 dropdown">
        <%= link_to '#', { class: 'dropdown-toggle d-flex align-items-center gap-2',
                           role: "button",
                           'data-bs-toggle': "dropdown",
                           'aria-expanded': "false" } do %>
          <span><%=t(:theme) %></span>
          <span class="current-theme-icon"></span>
        <% end %>
        <ul class="dropdown-menu">
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="light">
              <span class="icon">☀️</span>
              <%=t(:light) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="dark">
              <span class="icon">🌙</span>
              <%=t(:dark) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="auto">
              <span class="icon">🌓</span>
              <%=t(:auto) %>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="row">
  <div class="col-12">
    <% if ['admin/users'].include?(params[:controller]) %>
      <%= render 'admin/users/nav' %>
    <% end %>
    <% if ['admin/blogs','admin/blog_categories'].include?(params[:controller]) %>
      <%= render 'admin/blogs/nav' %>
    <% end %>
    <% if ['admin/notices','admin/blogs','admin/histories','admin/galleries'].include?(params[:controller]) %>
      <%= render 'admin/notices/nav' %>
    <% end %>
    <ul id="top-menu">
      <% if admin_signed_in? %>
        <li id="admin-info">
            <% if current_admin.admin_picture.present? %>
              <%= image_tag(current_admin.admin_picture.picture.small_thumb.url, { :height => 50, :width => 50 }) %>
            <% end %>
            <span class="text-dark"><%= current_admin.name %></span>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, :id => "p_logout", :method => :delete do %>
            <i class="material-icons" style="font-size:35px;vertical-align:middle">highlight_off</i><span><%= t(:logout) %></span>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_admin_session_path do %>
            <i class="material-icons">login</i><span><%= t(:login) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/admin/_login_footer.html.erb
<%
  l_class='dropdown-item d-flex align-items-center'

  ko_class=l_class+' ko'
  en_class=l_class+' en'
  zh_cn_class=l_class+' zh-CN'

  case session[:locale].to_s
  when 'en'
    en_class+=' active'
  when 'zh-CN'
    zh_cn_class+=' active'
  else
    ko_class+=' active'
  end

  puts session[:locale]
%>
<footer>
  <div class="container">
    <ul class="row justify-content-center">
      <li class="col-6 text-center text-xl-start">
        <address class="col-12 text-center">
          <a href="https://www.jedaeroweb.co.kr" target="_blank"><%=t(:jedearoweb) %></a>
          &nbsp;&nbsp; CopyLeft. 2020, jedaeroweb. All wrongs reserved.
        </address>
      </li>
      <!--  <li class="col-6 col-lg-4 dropdown">
        <%= link_to '#', { class: 'dropdown-toggle',role:"button",'data-bs-toggle': "dropdown",'aria-expanded':"false"} do %>
          <%=t(:language) %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <%=link_to '🇰🇷 한국어', url_for(:locale => 'ko'),:class=>ko_class,:'aria-pressed'=>"true" %>
          </li>
          <li>
            <%=link_to '🇺🇸 english', url_for( :locale => 'en'),:class=>en_class,:'aria-pressed'=>"false" %>
          </li>
          <li>
            <%=link_to '🇨🇳 汉语', url_for( :locale => 'zh-CN'),:class=>zh_cn_class,:'aria-pressed'=>"false" %>
          </li>
        </ul>
      </li> -->
      <li class="col-6 text-center text-xl-start">
        <%= link_to '#', { class: 'dropdown-toggle d-flex align-items-center gap-2',
                           role: "button",
                           'data-bs-toggle': "dropdown",
                           'aria-expanded': "false" } do %>
          <span><%=t(:theme) %></span>
          <span class="current-theme-icon"></span>
        <% end %>
        <ul class="dropdown-menu">
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="light">
              <span class="icon">☀️</span>
              <%=t(:light) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="dark">
              <span class="icon">🌙</span>
              <%=t(:dark) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="auto">
              <span class="icon">🌓</span>
              <%=t(:auto) %>
            </button>
          </li>
        </ul>
      </li>

    </ul>
  </div>
</footer>

app/views/layouts/admin/_login_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1><%= link_to root_path do %>
            <span class="logo"><%= t(:service_name) %></span>
          <% end %>
        </h1>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%= t(:service_name) %></title>
  <meta name="description" content="<%= t(:service_name) %>">
  <meta name="author" content="Sleeping-Lion">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
  <%= stylesheet_link_tag "admin", :media => "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "actiontext", :media => "all", "data-turbolinks-track" => true %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <%= render :partial => 'layouts/admin/aside' %>
    <div class="col-12 col-md-9 col-lg-10 col-xl-11">
      <%= render :partial => 'layouts/admin/header' %>
      <div id="mom" class="row">
        <div id="main" class="col-12">
          <div class="sub-main p-3 p-lg-4 p-xl-5">
            <%= render :partial => 'layouts/notice', :locals => { :notice => notice, :alert => alert } %>
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render :partial => 'layouts/admin/footer' %>
    </div>
  </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
<%= javascript_importmap_tags %>
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%=t(:service_name)%></title>
  <meta name="description" content="<%=t(:service_name)%>">
  <meta name="author" content="Sleeping-Lion">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag "admin", :media => "all", "data-turbolinks-track" => true %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body id="anon_body">
<div id="mom">
  <%= render :partial => 'layouts/admin/login_header' %>
  <main id="main" class="container">
    <div class="sub-main">
      <%= render :partial => 'layouts/notice', :locals => { :notice => notice, :alert => alert } %>
      <%= yield %>
    </div>
  </main>
</div>
<%= render :partial => 'layouts/admin/login_footer' %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
<%= javascript_importmap_tags %>
</body>
</html>

app/views/layouts/admin/popup.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <%= yield %>
  </div>
</div>