config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'
  resources :comments, only: [:create, :destroy]

  resources :blogs do
    member do
      put 'like', to: 'blogs#upvote'
      put 'dislike', to: 'blogs#downvote'
    end
  end

  resources :notices do
    member do
      put 'like', to: 'notices#upvote'
      put 'dislike', to: 'notices#downvote'
    end
  end

  resources :talks do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
  end

  resources :questions do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
    resources :answers
  end

  resources :galleries
  resources :markets
  resources :jobs
  resources :user_point_logs

  #intro
  get 'intro', :to=>'intro#index', as: 'intro'
  get 'privacy', :to=>'intro#privacy', as: 'privacy'
  get 'agreement', :to=>'intro#agreement', as: 'agreement'
  get 'mypage',:to=>'users#index', as: 'mypage'
  get 'tags/:tag', to: 'tags#index', as: :tag

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리사용자
  devise_for :admins, :controllers => {  :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'complete',:sign_in => 'login', :sign_out => 'logout'}

  # 관리자
  scope 'admin', module: 'admin', as: 'admin' do
    root to: 'home#index'

    resources :admins
    resources :users
    resources :galleries
    resources :markets
    resources :jobs
    resources :talks
    resources :galleries
    resources :blogs
    resources :comments
    resources :notices
    resources :questions
    resources :answers
    resources :blogs
    resources :blog_categories
  end
end

app/models/talk.rb
class Talk < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content

  validates_presence_of :title
  belongs_to :user, counter_cache: true
  has_many :talk_pictures, dependent: :destroy
  accepts_nested_attributes_for :talk_pictures, :allow_destroy => true
end

app/controllers/admin/talks_controller.rb
class Admin::TalksController < Admin::AdminController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @talk_count = Talk.count
    @talks = Talk.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talks }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @talk = Talk.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @talk = Job.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to [:admin, @talk], notice: t(:message_success_create) }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render action: 'new' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to [:admin, @talk], notice: t(:message_success_update) }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render action: 'edit' }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_talk
    @talk = Talk.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def talk_params
    params.require(:talk).permit(:title, :size, :enable)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  #impressionist :actions => [:show]
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_talk, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /talks
  # GET /talks.json
  def index
    if params[:search_detail].present?
      session[:search_detail]=1
    else
      if params[:search_summary].present?
        session.delete(:search_detail)
      end
    end

    if params[:list_type].present?
      if params[:list_type]=='list'
        session[:talk_list_type]='list'
      else
        session[:talk_list_type]='module'
      end
    end

    params[:per_page] = 12 unless params[:per_page].present?

    condition = { enable: true }

    @talk_count = Talk.where(condition).count
    @talks = Talk.where(condition).page(params[:page]).per(params[:per_page]).order('id desc')


    respond_to do |format|
      format.html # _slide.html.erb
      format.json { render json: @talks }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comment  = Comment.build_from(@talk, current_user, "")

    @meta_keywords=@talk.tag_list+t(:meta_keywords)
    @title=@talk.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /talks/new
  def new
    @talk = Talk.new
    @talk.talk_pictures.build
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'blog was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url, notice: 'blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    respond_to do |format|
      if @talk.liked_by current_user
        format.html { redirect_to talk_path(@talk), :notice => t(:message_success_recommend)}
        format.json { render :json => {vote_up: @talk.cached_votes_up}}
      else
        format.html { render :action => "index" }
        format.json { render :json => @talk.errors, :status => :unprocessable_entity }
      end
    end
  end

  def downvote
    respond_to do |format|
      if @talk.downvote_from current_user
        format.html { redirect_to talk_path(@talk), :notice => t(:message_success_recommend)}
        format.json { render :json => {vote_up: @talk.cached_votes_down}}
      else
        format.html { render :action => "index" }
        format.json { render :json => @talk.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_talk
    @talk = Talk.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def talk_params
    params.require(:talk).permit(:title, :description, :content, :tag_list, talk_pictures_attributes: [:picture]).merge(user_id: current_user.id)
  end
end

app/views/talks/_form.html.erb
<%= form_with(model: talk, local: true) do |form| %>
  <% if talk.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <button type="button" class="btn-close close" data-bs-dismiss="alert" aria-label="Close"></button>
      <h2><%= pluralize(talk.errors.count, "error") %> prohibited this request from being saved:</h2>
      <ul>
        <% talk.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => 'form-control', :required => 'required' %>
      </div>
      <div class="form-group">
        <%= form.rich_text_area :content, style: 'min-height:20em' %>
      </div>
      <div class="form-group">
        <%= form.label :tag_list, "태그달기(콤마로 구분,#해시 넣지마세요)" %>
        <div>
          <%= form.text_field :tag_list, :class=>'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= form.fields_for :talk_pictures  do |pp| %>
          <%= pp.label :picture %>
          <%= pp.file_field :picture, :class => "form-control-file" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="d-grid gap-2">
    <%= form.submit :class => "btn btn-primary btn-block btn-lg" %>
  </div>
<% end %>

app/views/talks/_index.html.erb
<section class="talks">
    <div class="row">
      <div class="col-12 section-header">
        <h2><%= t(:talk,scope: [:activerecord,:models]) %></h2>
          <%=link_to talks_path,class: 'more-link' do %>
            <span><%=t(:more) %></span>
          <% end %>
      </div>
      <% unless @talk_count.zero? %>
        <% @talks.each do |talk| %>
            <%=render 'talks/index_media',talk: talk %>
        <% end %>
      <% else %>
        <div class="talk col-12">
          <%= t(:no_data) %>
        </div>
      <% end %>
    </div>
</section>

app/views/talks/_index_default.html.erb
<section class="row">
  <% unless @talk_count.zero? %>
    <% @talks.each do |talk| %>
      <%=render 'talks/index_media',talk: talk %>
    <% end %>
    <div class="col-12">
      <%= paginate @talks %>
    </div>
  <% else %>
    <div class="question col-12">
      <%= t(:no_data) %>
    </div>
  <% end %>
  <div class="col-12">
    <%=link_to t(:new_talk),new_talk_path,class: 'btn btn-primary btn-large' %>
  </div>
</section>

app/views/talks/_index_list.html.erb
<div class="row">
  <div class="col-12">
    <div id="ad-main" class="table-responsive">
      <table class="table table-striped" data-controller="click-redirect">
        <colgroup>
          <col>
          <col>
          <col>
          <col>
          <col style="width:100px">
          <col style="width:220px">
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th><%= t(:user_id, scope: [:activerecord, :attributes, :blog]) %></th>
          <th><%= t(:blog_category_id, scope: [:activerecord, :attributes, :blog]) %></th>
          <th><%= t(:title, scope: [:activerecord, :attributes, :blog]) %></th>
          <th class="text-end"><%= t(:picture, scope: [:activerecord, :attributes, :blog_picture]) %></th>
          <th class="text-end"><%= t(:label_count) %></th>
          <th class="text-end"><%= t(:created_at, scope: [:activerecord, :attributes, :blog]) %></th>
        </tr>
        </thead>
        <tbody>
        <% unless @talk_count.zero? %>
          <% @talks.each do |talk| %>
            <tr data-action="click->click-redirect#rowClick">
              <td><%=display_user_photo(talk.user) %>&nbsp;&nbsp;<%= talk.user.name.truncate_bytes(16) %></td>
              <td></td>
              <td>
                <% if talk.comment_threads.count.zero? %>
                  <%= link_to talk.title, talk, data: { action: "click->click-redirect#rowLink"} %>
                  <% else %>
                <%= link_to talk.title+'['+talk.comment_threads.count.to_s+']', talk, data: { action: "click->click-redirect#rowLink"} %>
                  <% end  %>
              </td>
              <td class="text-end">
                <% if talk.talk_pictures_count.zero? %>
                  -
                <% else %>
                  <%= image_tag talk.talk_pictures[0].picture.small_thumb.url,class: 'figure-img img-fluid rounded'  %>
                <% end %>
              </td>
              <td class="text-end"><%= talk.impressionist_count(:filter => :ip_address) %></td>
              <td class="text-end text-secondary"><%= time_ago_in_words talk.created_at.to_date %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div id="sl_bottom_menu">
        <%= paginate @talks %>
      </div>
    </div>
  </div>
  <div class="col-12">
    <%=link_to t(:new_talk),new_talk_path,class: 'btn btn-primary btn-large' %>
  </div>
</div>

app/views/talks/_index_media.html.erb
<article class="talk col-12 col-sm-6 col-md-4 col-xl-3 col-xxl-2" data-controller="click-redirect" data-action="click->click-redirect#mediaClick">
  <div class="row">
    <div class="col-12">
      <% unless talk.talk_pictures_count.zero? %>
        <figure class="figure">
          <%= image_tag talk.talk_pictures[0].picture.medium_thumb.url, width:200, height:200,class: 'figure-img img-fluid rounded'  %>
        </figure>
      <% end %>
    </div>
    <div class="col-12">
      <div class="media rounded-2 p-3">
        <h3>
          <% if talk.comment_threads.count.zero? %>
            <%= link_to truncate(talk.title,length: 25), talk_path(talk) %>
            <% else %>
          <%= link_to truncate(talk.title,length: 25)+'['+talk.comment_threads.count.to_s+']', talk_path(talk) %>
            <% end %>
            </h3>
        <%= link_to talk_path(talk) do %>
        <%=truncate(strip_tags(talk.content.to_s), escape: false, length: 50)  %>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/talks/_search_form.html.erb
<div class="col-12">

</div>

app/views/talks/_search_form_detail.html.erb
<div class="col-12">
  <div class="card">
    <div class="card-body" style="margin-bottom:10px">
      <div class="form-row">
        <div class="col-12" style="margin-bottom:20px">
      <h3 class="float-start">상세검색</h3>
      <%=form_tag blogs_path,:method => 'get', :class=>"float-right" do %>
        <input type="hidden" name="search_summary" value="1">
        <% if @blog.present? %>
          <input type="hidden" name="product" value="<%=@blog.id %>">
        <% else %>
          <%  if @blog_category.present? %>
            <input type="hidden" name="category" value="<%=@blog_category.id %>">
          <% end %>
        <% end %>
        <button type="submit" value="close" style="background-color: Transparent;background-repeat:no-repeat;border: none; "><i class="material-icons">close</i></button>
      <% end %>
        </div>
      </div>
      <%=form_tag blogs_path,{method:'get', class: 'search_form_show'} do %>
        <input type="hidden" name="search" value="1">
        <div class="form-row">
        </div>
        <div class="form-row">
        </div>


        <%=submit_tag t(:search),class: 'btn btn-primary btn-lg btn-block btn-search' %>
      <% end %>
    </div>
  </div>


</div>

app/views/talks/edit.html.erb
<section id="edit-talk">
  <div class="row">
    <h2 class="col-12"><%=t(:edit_talk) %></h2>
    <div class="col-12">
      <%= render 'form', talk: @talk %>
    </div>
  </div>
</section>

app/views/talks/index.html.erb
<%
  render_templete='talks/index_default'

  if session[:talk_list_type].present?
    if session[:talk_list_type]=='list'
      render_templete='talks/index_list'
    end
  end

%>
<div id="questions">
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals=>{:errors=>nil, :notice=>notice,:alert=>alert} %>
  </div>
  <div class="row">
    <% if session[:search_detail].present? %>
      <%=render 'talks/search_form_detail' %>
    <%  else %>
      <%=render 'talks/search_form' %>
    <% end %>
    <div class="col-12">
      <ul class="type-selector">
        <li><%=link_to url_for(list_type: 'list') do %><span class="material-icons">view_list</span><% end %></li>
        <li><%=link_to url_for(list_type: 'module') do %><span class="material-icons">view_module</span><% end %></li>
      </ul>
    </div>
    <div class="col-12">
      <h2 class="float-start hidden-title"><%= t(:talk,scope: [:activerecord,:models]) %></h2>
      <div class="float-end">
        <p class="summary text-end">
          <span id="list_count" style="display:none"><%= @talk_count %></span>
          <%= raw t(:there_are_n_talks, count: @talk_count) %>
        </p>
      </div>
    </div>
  </div>
  <%=render render_templete %>
</div>

app/views/talks/new.html.erb
<section id="add-talk">
  <div class="row">
    <h2 class="col-12"><%=t(:new_talk) %></h2>
    <div class="col-12">
      <%= render 'form', talk: @talk %>
    </div>
  </div>
</section>

app/views/talks/show.html.erb
<div id="show-question">
  <div class="row">
    <article class="col-12 mb-3" itemscope itemprop="article" itemtype="http://schema.org/Article">
      <div class="sl_content_header">
        <h3 itemprop="name"><%= @talk.title %></h3>
        <p class="text-end">
          <span><%= t(:user_id, scope: [:activerecord, :attributes, :blog]) %> : <%=display_user_photo(@talk.user) %>&nbsp;&nbsp;<%= @talk.user.name.truncate_bytes(16) %></span>
          <span style="margin-left:3rem"><%= t(:created_at, scope: [:activerecord, :attributes, :question]) %> : <%= I18n.l @talk.created_at.to_date, :format => :long %></span>
        </p>
      </div>
      <div class="sl_content_main">
        <div class="sl_content_text" itemprop="text"><%=simple_format sanitize(@talk.content.to_s.gsub(/\n/, '<br />'), :tags => %w(br img a)) %></div>
        <div class="vote">
          <% if user_signed_in? %>
            <%= link_to like_talk_path(@talk), method: :put do %>
            <span class="material-icons
              <% if current_user.voted_for? @talk %> already-vote
              <% end %>">thumb_up</span> <span class="text"><%= @talk.cached_votes_up %></span>
            <% end %>
          <% else %>
            <%= link_to like_talk_path(@talk), { method: :put, :class => "confirm_login" } do %>
              <span class="material-icons">thumb_up</span> <span class="text"><%= @talk.cached_votes_up %></span>
            <% end %>
          <% end %>
        </div>
      </div>
      <% unless @talk.tags.count.zero? %>
      <p>
        Tags: <%= raw @talk.tags.map { |t| link_to t, tag_path(:tag=>t.name) }.join(', ') %>
      </p>
      <% end %>
    </article>
  </div>
  <script>
      function showHide(id) {
          var obj = document.getElementById(id);
          if (obj.style.display == 'none')
              obj.style.display = 'block';
          else
              obj.style.display = 'none';
      }
  </script>
  <div class="row">
    <div class="col-12">
      <%= render partial: "comments/templete", locals: {commentable: @talk, new_comment: @comment} %>
    </div>
  </div>
  <div class="row">
    <div class="btn-group btn-group-lg col-12" role="group" style="margin-top:3rem">
      <%=link_to t(:link_list),talks_path,{class: 'btn btn-secondary btn-large btn-block'} %>
    </div>
  </div>
</div>
<% content_for :json_ld do %>
  <script type="application/ld+json">
    <%= raw(JSON.pretty_generate(article_json_ld(@talk))) %>
  </script>
<% end %>