config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'feed',:to=>'home#feed'
  resources :comments, only: [:create, :destroy]

  resources :blogs do
    member do
      put 'like', to: 'blogs#upvote'
      put 'dislike', to: 'blogs#downvote'
    end
  end

  resources :notices do
    member do
      put 'like', to: 'notices#upvote'
      put 'dislike', to: 'notices#downvote'
    end
  end

  resources :talks do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
  end

  resources :questions do
    member do
      put 'like', to: 'talks#upvote'
      put 'dislike', to: 'talks#downvote'
    end
    resources :answers
  end

  resources :galleries
  resources :markets
  resources :jobs
  resources :user_point_logs

  #intro
  get 'intro', :to=>'intro#index', as: 'intro'
  get 'privacy', :to=>'intro#privacy', as: 'privacy'
  get 'agreement', :to=>'intro#agreement', as: 'agreement'
  get 'mypage',:to=>'users#index', as: 'mypage'
  get 'tags/:tag', to: 'tags#index', as: :tag

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords" }, :path_names => { :sign_up => 'new', :sign_in => 'login', :sign_out => 'logout' }

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  # 관리사용자
  devise_for :admins, :controllers => {  :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'complete',:sign_in => 'login', :sign_out => 'logout'}

  # 관리자
  scope 'admin', module: 'admin', as: 'admin' do
    root to: 'home#index'

    resources :admins
    resources :users
    resources :galleries
    resources :markets
    resources :jobs
    resources :talks
    resources :galleries
    resources :blogs
    resources :comments
    resources :notices
    resources :questions
    resources :answers
    resources :blogs
    resources :blog_categories
  end
end

app/views/admin/admins/_form.html.erb
<%= form_with(model: [:admin, admin], local: true, :html => { :id => "user_form" }) do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, :class => "form-control", :required => "required" %>
      </div>
      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :phone, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :birthday %>
        <%= form.date_field :birthday, :class => "form-control" %>
      </div>
    </div>
  </div>
  <%= form.submit :class => "btn btn-primary btn-lg btn-block" %>
<% end %>

app/views/admin/admins/_nav.html.erb
<%
  a_class='nav-link'
  b_class='nav-link'
  c_class='nav-link'
  d_class='nav-link'
  e_class='nav-link'
  f_class='nav-link'
  g_class='nav-link'

  if params[:controller]=='admin/admins'
    a_class+=' active'
  end

  if params[:controller]=='admin/specialities'
    b_class+=' active'
  end

  if params[:controller]=='admin/speciality_categories'
    c_class+=' active'
  end

  if params[:controller]=='admin/sizes'
    d_class+=' active'
  end

  if params[:controller]=='admin/materials'
    e_class+=' active'
  end

  if params[:controller]=='admin/addresses'
    f_class+=' active'
  end

  if params[:controller]=='admin/address_levels'
    g_class+=' active'
  end
%>
<div class="col-12">
  <nav class="sub-nav">
    <ul class="nav nav-pills">
      <li class="nav-item"><%=link_to t(:admin, scope: [:activerecord, :models]),admin_admins_path,{:class=>a_class} %></li>
      <li class="nav-item"><%=link_to t(:speciality, scope: [:activerecord, :models]),admin_specialities_path,{:class=>b_class} %></li>
      <li class="nav-item"><%=link_to t(:speciality_category, scope: [:activerecord, :models]),admin_speciality_categories_path,{:class=>c_class} %></li>
      <li class="nav-item"><%=link_to t(:size, scope: [:activerecord, :models]),admin_sizes_path,{:class=>d_class} %></li>
      <li class="nav-item"><%=link_to t(:material, scope: [:activerecord, :models]),admin_materials_path,{:class=>e_class} %></li>
      <li class="nav-item"><%=link_to t(:address, scope: [:activerecord, :models]),admin_addresses_path,{:class=>f_class} %></li>
      <li class="nav-item"><%=link_to t(:address_level, scope: [:activerecord, :models]),admin_address_levels_path,{:class=>g_class} %></li>
    </ul>
  </nav>
</div>

app/views/admin/admins/edit.html.erb
<div id="edit_admin" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:edit_admin) %></h2>
  </div>
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => { :errors => @admin.errors, :notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', admin: @admin %>
    </div>
  </div>
</div>

app/views/admin/admins/index.html.erb
<article class="col-12">
  <h2 class="float-start"><%= t(:admin_list) %></h2>
  <div class="float-end">
    <p class="summary">
      <span id="list_count" style="display:none"><%= @admin_count %></span>
      <%= raw t(:there_are_n_admins, count: @admin_count) %>
    </p>
  </div>
  <table class="table table-striped table-hover">
    <colgroup>
      <col style="width:120px">
      <col>
      <col>
      <% if can?(:update, User) || can?(:delete, User) %>
        <col<%= manage_width(User) %>>
      <% end %>
    </colgroup>
    <thead class="thead-default">
    <tr>
      <th class="text-center"><%= t(:enable, scope: [:activerecord, :attributes, :user]) %></th>
      <th><%= t(:name, scope: [:activerecord, :attributes, :user]) %></th>
      <th class="text-end"><%= t(:updated_at, scope: [:activerecord, :attributes, :user]) %></th>
      <% if can?(:update, User) || can?(:delete, User) %>
        <th class="text-center"><%= t(:manage) %></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% unless @admin_count.zero? %>
      <% @admins.each_with_index do |admin, index| %>
        <tr>
          <td>
            <div class="custom-control custom-switch">
              <input type="checkbox" class="custom-control-input" id="user_display<%= index %>" value="<%= admin.id %>"
                     <% if admin.enable %> checked
              <% end %>>
              <label class="custom-control-label" for="user_display<%= index %>">
                <% if admin.enable %> <%= t(:display) %>
                <% else %><%= t(:hidden) %>
                <% end %> </label>
            </div>
          </td>
          <td><%= link_to admin.name, admin_admin_path(admin) %></td>
          <td class="text-end"><%= I18n.l admin.created_at.to_date, :format => :long %></td>
          <% if can?(:update, admin) or can?(:delete, user) %>
            <td class="text-end">
              <% if can? :update, admin %>
                <%= link_to edit_admin_admin_path(admin), :class => "btn btn-secondary" do %>
                  <%= t(:edit) %>
                <% end %>
              <% end %>
              <% if can? :delete, admin %>
                <%= link_to admin_admin_path(admin), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
                  <%= t(:delete) %>
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="7" class="text-center"><%= t(:no_data) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @admins %>
  <% if can? :create, Admin %>
  <%= link_to t(:add), new_admin_admin_path, :class => "btn btn-primary" %>
  <% end %>
</article>

app/views/admin/admins/new.html.erb
<div id="new_admin" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:new_admin) %></h2>
  </div>
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => { :errors => @admin.errors, :notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', admin: @admin %>
    </div>
  </div>
</div>

app/views/admin/admins/show.html.erb
<section id="show-user" class="col-12">
  <div class="row">
    <%= render :partial => 'layouts/notice', :locals => { :errors => @admin.errors, :notice => notice, :alert => alert } %>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <h3 class="card-header"><%=@admin.name %></h3>
        <div class="card-body">
          <dl>
            <dt><%= t(:phone, scope: [:activerecord, :attributes, :admin]) %></dt>
            <dd><%= @admin.phone %></dd>
            <dt><%= t(:created_at, scope: [:activerecord, :attributes, :admin]) %></dt>
            <dd><%= I18n.l @admin.created_at.to_date, :format => :long %></dd>
            <dt><%= t(:updated_at, scope: [:activerecord, :attributes, :admin]) %></dt>
            <dd><%= I18n.l @admin.updated_at.to_date, :format => :long %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      <%= link_to t(:link_list), admin_admins_path, class: 'btn btn-secondary' %>
    </div>
    <div class="col-12 col-xl-6 text-end">
      <%= link_to t(:edit), edit_admin_admin_path(@admin), class: 'btn btn-secondary' %>
      <%= link_to t(:delete), admin_admin_path(@admin), class: 'btn btn-danger' %>
    </div>
  </div>
</section>